### ISSUE TITLE
Regression: Windows build on devel started timing out; used to build in 30mins

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/nightlies#17]
Win 32-bit used to build fine on https://github.com/nim-lang/Nim/commit/abad758a7eff72e9f97224c400e1b48d09ecd97a (devel) on : https://travis-ci.org/nim-lang/nightlies/jobs/476679277
It started failing on https://github.com/nim-lang/Nim/commit/11050d110461edc3646a66b8afefb7907187f78c (devel) the next day on : https://travis-ci.org/nim-lang/nightlies/jobs/477664314

Range of commits: https://github.com/nim-lang/Nim/compare/abad758a...11050d11

~~I haven't done bisect but this seems to be a likely candidate to cause this regression: https://github.com/nim-lang/Nim/commit/c60916a2aff121fc0220f9452803a7bcfb6300d0. That might explain why builds for non-Windows OSes is happening in the Windows build.~~ .. or probably not, because that commit adds a `runCI` target to `koch`, which is not used in nightlies.

/cc @Araq @genotrance ~~@timotheecour~~

**Comment by kaushalmodi** [comment]
Discussion on IRC: https://irclogs.nim-lang.org/15-01-2019.html#17:23:19

**Comment by genotrance** [comment]
This is breaking due to this change:

https://github.com/nim-lang/Nim/commit/c60916a2aff121fc0220f9452803a7bcfb6300d0#diff-cdc1b5c3c94ae8670cc9a495b8647ba8L53

```nim
let kochExe* = os.getAppFilename()
```

This works fine when running `koch`, but `winrelease` leverages `koch.nim` so `kochExe` now points to `winrelease` instead. Hence, `winrelease` calls itself recursively when invoking `koch` calls.
