### ISSUE TITLE
nightlies for linux x64

### ISSUE THREAD

**Issue by mattgodbolt** [nim-lang/nightlies#31]
Hi, I administrate nim.godbolt.org and we used to install nightly nim builds by grabbing them from here. However, the linux_x64 version is no longer built here, it seems.

Is there a spot we can pick up x86_64 binaries?

**Comment by narimiran** [comment]
> the linux_x64 version is no longer built here, it seems.

Oh, Nim devel (1.3.1) has been failing CIs, without us noticing! 

> Is there a spot we can pick up x86_64 binaries?

Once we fix the failing tests, you'll be able to pick it up here again, like before.

----

Btw, from what I've seen on your website, you're using (just) Nim 1.0.4? No other Nim versions?

The nightlies are building the latest devel version (1.3.x, currently failing), version 1.2.x (the latest stable), and version 1.0.x.

**Comment by narimiran** [comment]
> We basically grab https://api.github.com/repos/nim-lang/nightlies/releases/latest and look for the linux_x64 binaries.

This should work now.

**Comment by mattgodbolt** [comment]
Confirmed! thanks

**Comment by mattgodbolt** [comment]
Re: Compiler Explorer; it should bounce soon and pick up nims 1.2.0 and 1.0.*. Once I fix my scripts I'll pick up the 1.3.* again too.

**Comment by mattgodbolt** [comment]
HIi @narimiran -- the linux_x64 binaries are missing again: can you have a look please?

**Comment by narimiran** [comment]
> can you have a look please?

Will do. I'll ping you once it is fixed.

**Comment by mattgodbolt** [comment]
Any luck? I see even fewer things are building right now :)

**Comment by narimiran** [comment]
Fewer things?

The only builds missing currently are Nim devel (1.3.5) on Linux, everything else is building fine, including the upcoming 1.2.6 release: https://github.com/nim-lang/nightlies/releases/tag/2020-07-29-version-1-2-bf320ed

**Comment by apmorton** [comment]
I think the issue for us is that because the releases stream here is a mixed bag of different branches https://api.github.com/repos/nim-lang/nightlies/releases/latest is unreliable.

There is no simple, stable location (that we are currently aware of) which we can check to get the latest 1.2 nightly (or any other specific branch). We would need to grab https://api.github.com/repos/nim-lang/nightlies/releases and parse the whole thing to find the latest release with the specific branch name we care about _that actually has a linux64 asset_.

Its definitely not ideal when compared to how other projects tend handle automated nightly releases, which is usually a variation on:
  - a stable URL that always gives the latest build for a specific branch/arch
  - a manifest file that gives the locations to the latest build for each branch/arch

**Comment by narimiran** [comment]
@genotrance @alaviss can do something about the concerns mentioned above?

**Comment by alaviss** [comment]
Maybe we can setup some tags in the format of `<branch>-<target>`, then have the CI update the tag to the latest build as they're made available. Shouldn't be too hard to do.

**Comment by narimiran** [comment]
> the linux_x64 binaries are missing again

@mattgodbolt This should be fixed now, thanks to @alaviss and our new CI process.

Here are the latest devel nightlies, including `linux_x64`: https://github.com/nim-lang/nightlies/releases/tag/2020-08-28-devel-fb58066b61b14f4a1d6cdb0f4a8f0a9ea4174d82

**Comment by alaviss** [comment]
@mattgodbolt @apmorton We now publish `latest-` aliases for branches that nightlies track. You can find the latest tag for branch version-1-2 [here](https://github.com/nim-lang/nightlies/releases/tag/latest-version-1-2). The `latest-` tag is published only when binaries for all OS/architecture combination is built, so you can be sure that the target you need is always there.

**Comment by genotrance** [comment]
Need to update choosenim to use this tag - related code here:

https://github.com/dom96/choosenim/blob/13db8b15abfa92fe553523e9130be5e983976a2a/src/choosenimpkg/utils.nim#L120-L141

cc @dom96

**Comment by apmorton** [comment]
Great, thanks!

The only thing that would make this better is if the asset names were static.
As it stands they contain the full nim version number, which means they will vary over time as the minor version gets bumped within a branch.

Ideally for these "latest" tags you could publish the assets without the version number (or fake partial version number such as `1.4.x`), so anyone wanting to get the latest linux_x64 build of the 1.4 branch could just:

```
wget https://github.com/nim-lang/nightlies/releases/download/latest-version-1-4/nim-linux_x64.tar.xz
```

right now the full asset url is:
```
https://github.com/nim-lang/nightlies/releases/download/latest-version-1-4/nim-1.3.7-linux_x64.tar.xz
```
which will break once nim bumps to `1.3.8` (or beyond)

However, what we have now is workable - we can grab https://api.github.com/repos/nim-lang/nightlies/releases/tags/latest-version-1-4 and parse the output looking for an asset with "linux_x64" in order to find the full url

**Comment by alaviss** [comment]
@apmorton 

> Ideally for these "latest" tags you could publish the assets without the version number

Wish granted: https://github.com/alaviss/nightlies/releases/tag/latest-version-1-4

The next nightly cycle will have them here. Currently this repo tripped API limits because of excessive builds :P
